server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: weather-project
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:elyor1202}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    enabled: true
